# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoogleDrive' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoogleDrive
  pod 'GoogleSignIn', '4.4.0'
  pod 'GoogleAPIClientForREST/Drive'

end
